{% set name = "ssh2-python" %}
{% set version = "0.27.0" %}
{% set sha256 = "b824900cdd0a870db6f2ee013e768a42f22c5004e4104aa1524987ead1aa9726" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: b824900cdd0a870db6f2ee013e768a42f22c5004e4104aa1524987ead1aa9726

build:
  skip: true  # [win]
  number: 1
  script:
    - SYSTEM_LIBSSH2=1 pip install . -vv
requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - libssh2 1.8.*
  run:
    - python
    - libssh2 1.8.*

test:
  imports:
    - ssh2.session

about:
  home: http://github.com/ParallelSSH/ssh2-python
  license: LGPL-2.1
  license_family: LGPL
  license_file: LICENSE
  summary: 'Super fact SSH library. Based on libssh2.'

  description: |
    Super fast SSH2 protocol library.

    ssh2-python provides Python bindings for libssh2.
    
    Its only dependency is the libssh2 library.
  dev_url: https://github.com/ParallelSSH/ssh2-python

extra:
  recipe-maintainers:
    - pkittenis
