travis:
  secure:
    BINSTAR_TOKEN: TlKR9JBI/6UqdBIDA9dkESYgywzIk5Ptp2XFq8GXatM3XL+ZEq40QsS/Q6fY5XBRH+UyB0g9fW7keacy3fqQ2Yk0x2bDWIy3i73Cz2TloaDyKv5C1H59HMrGzLQuk/SdV9Ql7q/ftjf8v48gwVV7XsPt6Z3YS4eC72hpr7omXX4hlMa7idqhne2m1Vvry4XJI8ddsxShxWlrfBy6Wv1OCAa78aRsq4YOAwM1OozblodRZswQREynGI3SgK5A52DpAF8F7ImLpEH9JLpb/0jAmxAfiwXsaMP3xC/oRKQe/EYGnLgEWaUgK7OE8yXCHkV6e9i3qouqBQ+Q9BQTPK+EwfNxgxOp151uxLt/PI5l3har8sthy48G0LSzhwJLwNSvvnZ5/5jGGy4oZp/NQWQHJM96ZCu46YoUE3M381o14VZWMkkFqfLSVgbJOUOaJL2z3Gvfv/R1flpX+bHluna4Gl84cxrIJWEwZNVhp+rKUFiPMulGl0qH9o0WUmFcPNZ4OdVhxeUm2ib83rH3D5JbYVEn+o/2cdJh0ElK3F0wZQYWS+RGPEdJSbIVOBv8D4Rn1neTHwIP4ASv07R3tE58+NEvjis4HxmtlTZeJ3/lDRxbcDa4xPp23qd36Z/7OS2S+6IQAOheFwTutSKi3lO+c0m2VvzHVTnsLL0c9JfrUTI=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
